version: '3.3'

services:

  database:
    image: postgres
    volumes:
      - ./database:/var/lib/postgresql/data

  django:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    links:
      - database
    volumes:
      - ./application:/root

  webserver:
      image: nginx
      links:
        - django
      volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
      environment:
        - VIRTUAL_HOST=example.com
        - VIRTUAL_PORT=80
        - LETSENCRYPT_HOST=example.com
        - LETSENCRYPT_EMAIL=email@example.com
    restart: unless-stopped

networks:
  default:
    external:
      name: webproxy
